server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vibraops-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vibraops-api
          __path__: /var/log/vibraops/api.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<logger>\S+) - (?P<level>\S+) - (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
      - labels:
          level:
          logger:

  - job_name: vibraops-predictions
    static_configs:
      - targets:
          - localhost
        labels:
          job: vibraops-predictions
          __path__: /var/log/vibraops/predictions.jsonl
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            prediction: prediction
            model_type: model_type
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          model_type: 