# Environment configuration for VibraOps Local Deployment
# Generated by Terraform

# Redis Configuration
REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}

# Monitoring URLs
PROMETHEUS_URL=${prometheus_url}
GRAFANA_URL=${grafana_url}
LOKI_URL=${loki_url}

# API Configuration
API_URL=${api_url}
API_PORT=8000

# Logging
LOG_LEVEL=INFO

# Model Configuration
MODEL_PATH=/app/models

# Environment
ENVIRONMENT=local 