global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # VibraOps API monitoring
  - job_name: 'vibraops-api'
    static_configs:
      - targets: ['vibraops-api:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # System metrics (node exporter would be added here)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 